version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "94:22:51:2e:48:90:2e:ff:7c:a0:80:1d:a0:6c:33:55"
      - run:
          name: Build and push backend application image
          command: |
            git clone https://github.com/kirubakarthikeyan/spring-petclinic-rest.git
            cd ./spring-petclinic-rest
            ./mvnw clean install
            TAG=v$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/petclinic_backend:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/petclinic_backend:$TAG
  deploy:
    docker:
      - image: cimg/base:2023.12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - add_ssh_keys:
          fingerprints:
            - "94:22:51:2e:48:90:2e:ff:7c:a0:80:1d:a0:6c:33:55"
      - run:
          name: Update docker image
          command: |
            URL=https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.5.2/kustomize_v4.5.2_linux_amd64.tar.gz
            curl -L $URL | tar zx
            [ -w /usr/local/bin ] && SUDO="" || SUDO=sudo
            $SUDO chmod +x ./kustomize
            $SUDO mv ./kustomize /usr/local/bin
            git clone https://github.com/kirubakarthikeyan/spring-cluster.git
            cd ./spring-cluster/kubernetes
            TAG=v$CIRCLE_BUILD_NUM
            kustomize edit set image $APP_NAME=$DOCKERHUB_USERNAME/petclinic_backend:$TAG
            git config user.email "$GITHUB_EMAIL"
            git config user.name "CircleCI User"
            git checkout main
            git add kubernetes/kustomization.yaml
            git commit -am "Bumps docker tag [skip ci]"
            git push origin main
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy
