version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "94:22:51:2e:48:90:2e:ff:7c:a0:80:1d:a0:6c:33:55"
      - run:
          name: Build and push backend application image
          command: |
            git clone https://github.com/kirubakarthikeyan/spring-petclinic-rest.git
            cd ./spring-petclinic-rest
            ./mvnw clean install
            TAG=v$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/petclinic_backend:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/petclinic_backend:$TAG
workflows:
  version: 2
  build:
    jobs:
      - build
